### ISSUE TITLE
TokenMod - Directional Low Light Fields Missing

### ISSUE THREAD

**Issue by Zierman** [Roll20/roll20-api-scripts#1100]
At the moment **TokenMod** cannot be used to set any directional low light fields.

Fields to add:
- [ ] **has_directional_low_light** (boolean)
- [ ] **directional_low_light_center** (degrees)
- [ ] **directional_low_light_total** (circleSegment)

_The fields to add are based on  the contents of the [Roll20 Help Center's **Updated Dynamic Lighting API Support** page](https://roll20.zendesk.com/hc/en-us/articles/360046490373-Updated-Dynamic-Lighting-API-Support#directional-vision-and-lighting-0-2)_

**Comment by Anduh** [comment]
@shdwjk

**Comment by Zierman** [comment]
See shdwjk/Roll20API#29

**Comment by shdwjk** [comment]
I'm traveling for the next week, but I'll take a look when I get a chance. Last I checked, the UDL settings for the API were a bit broken in the Roll20 side, so there might not be much I can do about it.

**Comment by Zierman** [comment]
> I'm traveling for the next week, but I'll take a look when I get a chance. Last I checked, the UDL settings for the API were a bit broken in the Roll20 side, so there might not be much I can do about it.
@shdwjk 

My recent testing supports the claim that the UDL API is broken on the Roll20 side. The proposed changes will only set the properties while no changes will graphically render due to this. Assuming that the documentation is accurately describing the intended API, the proposed changes *should* work as expected when the UDL API is fixed on Roll20’s side. Perhaps a acknowledgment of this issue on the help messages would be a good idea in the meantime so users understand the limitation.

**Comment by shdwjk** [comment]
Sorry, forgot all about this.  As it happens, the documentation is wrong.  Those 3 fields do not exist on graphic objects in Roll20.

**Comment by Anduh** [comment]
Have these been added now?

**Comment by shdwjk** [comment]
Yes, those are all present in TokenMod now.  There are still some UDL issues with the API, but they are on the Roll20 side and they have repro cases to fix them.  This issue can be closed.

**Comment by Zierman** [comment]
> Yes, those are all present in TokenMod now. There are still some UDL issues with the API, but they are on the Roll20 side and they have repro cases to fix them. This issue can be closed.

Sorry that it took so long for me to get back. I've closed the issue.
