### ISSUE TITLE
Remove older versions of script

### ISSUE THREAD

**Issue by Ulty** [Roll20/roll20-api-scripts#1360]
Hi,

Is it possible to remove older versions of one's script? I've got versions from 4 years ago, and I don't think they would be usable anyway. It would be nice to shorten a bit the list of older versions. And anyway, nothing is ever lost with git.

**Comment by Anduh** [comment]
You could update the `"previousversions"` list in `script.json` and remove the ancient version, removing them from the version selection menu.

**Comment by Ulty** [comment]
I did that once, a couple of years ago, and my change was reverted. So I figured this could be against Roll20 policy and I should ask.

**Comment by Ulty** [comment]
I tried again recently, and removing all versions seems to be accepted, now.
