### ISSUE TITLE
Pull 1495 (for Initiative Tracker Plus) does not seem to have been merged properly.

### ISSUE THREAD

**Issue by jaculpiii** [Roll20/roll20-api-scripts#1499]
[https://github.com/Roll20/roll20-api-scripts/pull/1495](https://github.com/Roll20/roll20-api-scripts/pull/1495)

This pull request doesn't seem to have merged properly, the files all look correct, script.json /1.29/initiative_tracker_plus.js both are correct but when loading "Latest" in the one-click version 1.28 is loaded and there is no option for 1.29 period.

@NicholasR77 It was suggested I mention you for this.

Please advise what I need to do to make things work.

Thanks,
Chuz

**Comment by NicholasR77** [comment]
Hey Chuz! Apologies for the trouble here, but we haven't gotten a chance to do a deploy on our main application for the latest version of the master branch in this repo. We're going to try and get a deploy going today and look at how we make API script deploys more consistent going forward. Thanks for checking in!

**Comment by NicholasR77** [comment]
@jaculpiii Ok we just finished a deploy and everything we should be available now. Thanks again for your patience!
