### ISSUE TITLE
TempHPandStatus fails to load

### ISSUE THREAD

**Issue by JRobber** [Roll20/roll20-api-scripts#150]
I pasted the TempHPandStatus.js file into the API and when the sandbox resets it files to list the version number indicating the script has loaded.

Other scripts are working.

The code does not actually work in a game session either.

![image](https://cloud.githubusercontent.com/assets/6341880/9560957/58f5bb1e-4dee-11e5-9a27-107ceb3e9107.png)

**Comment by shdwjk** [comment]
This is an older script and I haven't added the announce code to it to state it's version.  It also does not have fantastic configuration options.  By default, it looks at the 3rd bar (the one that is the left one when the token is selected, defaults to red).  When that bar is adjusted, it will add one of 3 different statuses depending on the ratio of current to max:
* half to max - Nothing
* 1 to half - broken heart
* -half+1 to 0 - Dead X
* -half - Crushed skull

If this isn't working for you, post in the API forum and I'll try to help you debug it.  I don't believe anyone watches the bugs here.
