### ISSUE TITLE
The RollStats script throws errors every single session

### ISSUE THREAD

**Issue by JamesMowery** [Roll20/roll20-api-scripts#160]
This error pops up every single session, regardless of whether or not we use the !rollstats command during the game. It then prevents other scripts from running.

<img width="1159" alt="screen shot 2015-09-19 at 2 15 49 am" src="https://cloud.githubusercontent.com/assets/868178/9977478/c6d4f268-5ed7-11e5-9a0a-b65bd4be77d7.png">

**Comment by shdwjk** [comment]
Hopefully the patch I just submitted will resolve this issue.

**Comment by shdwjk** [comment]
Generally speaking, you're better off posting in the API forum for bugs.

**Comment by JamesMowery** [comment]
Good to know. I'll post in the forum next time. Regardless, thanks for patching this. I'll definitely give it a whirl next game!

**Comment by JamesMowery** [comment]
Hey @shdwjk, I might have been a bit pre-emptive in the assumption that this is fixed. I posted on the forum about this: https://app.roll20.net/forum/post/2456741/rollstats-bug/?pageforid=2456741#post-2456741

However, it looks like I'm still getting the same error.
