### ISSUE TITLE
TokenLock failing when the Initiative counter is empty.

### ISSUE THREAD

**Issue by bpunya** [Roll20/roll20-api-scripts#334]
The TokenLock script immediately crashes if a token is moved and the turnorder window is empty. (both versions, 0.2.3 and 0.2.4).

The problem is on line 204:
`&& ( !state.TokenLock.config.allowMoveOnTurn || (( (JSON.parse(Campaign().get('turnorder'))||[{id:false}])[0].id) !== obj.id) )`

`JSON.parse(Campaign().get('turnorder'))||[{id:false}]` will never return `[{id:false}]`, so a "TypeError: Cannot read property 'id' of undefined" is thrown every time a token is moved when the turnorder window is empty.

**Comment by shdwjk** [comment]
Updated TokenLock to v0.2.5

Just sent a pull request to fix this. Thanks!
