### ISSUE TITLE
Typo causes announcer GM chat error

### ISSUE THREAD

**Issue by eddieblandon** [Roll20/roll20-api-scripts#350]
"Line 142: sendChat(accouncer, '/w gm Trap Notes:<br/>' + effect.notes);"

Getting error due to the name **accouncer** being incorrect, should be **announcer**.

**Comment by Cazra** [comment]
This bug will be fixed in It's A Trap 2.7. 
In future issues, please include the name of the script causing the issue in the issue's subject.

**Comment by Cazra** [comment]
This issue is now fixed. Someone please close it. @SteveKoontz
