### ISSUE TITLE
FFG-SWRPG-Dice-Roller Domain has expired

### ISSUE THREAD

**Issue by sirisaacnuketon** [Roll20/roll20-api-scripts#351]
The domain containing all the assets for this API addon has expired, I can't find any contact details for the team building it though. An alternative source should be found for the images.

**Comment by greggoman** [comment]
I can confirm it looks like galacticcampaigns that hosts the images has gone down. All the dice images aren't working for me either 
![image](https://cloud.githubusercontent.com/assets/12986614/18887382/c23ba630-84eb-11e6-8445-56024f7477d9.png)
