### ISSUE TITLE
Two scripts I've created have been merged to master but are not in the approved.yaml

### ISSUE THREAD

**Issue by RyanNerd** [Roll20/roll20-api-scripts#388]
Related to issue #386 
Is there a process that needs to happen to get a script to be included in the approved.yaml file?

These are the scripts I created that have been merged to master, but are not included in the approved.yaml:

- Markov
- Fumbler

**Comment by SteveKoontz** [comment]
Both scripts don't have their folder structure matching the script version. Markov script.json file is set to version "0.1.1" but the two version folders are "1.0" and "1.1". And Fumbler doesn't have any folders at all. If you update the folder structures I'll include them in the next deploy.

**Comment by RyanNerd** [comment]
Thanks @SteveKoontz 
I've created PR #393 and #394 that should make things right.
