### ISSUE TITLE
invalid byte sequence in UTF-8 - MythicGM 

### ISSUE THREAD

**Issue by pyromanci** [Roll20/roll20-api-scripts#416]
Received a report for someone who used my API, MythicGM they are getting the following error when they go into the script section of their campaign.
`ArgumentError: invalid byte sequence in UTF-8`

When I tired to use it does the same thing. Also clicking import does not work. However when you take the code and manually attach it to game it works just fine. 

So something is broken on the roll20 side of things that when the script is being added to games.

**Comment by shdwjk** [comment]
Actually, it's likely something with the data of the script that gets repaired by the browser when you paste it in the text field.  Line 301 of your script has 2 non-ascii characters that are probably what is causing the problem.  The characters on either side of the yes.  

Here is a hex dump of line 301, on the 4th line from the bottom you can see the .yes., if you look at the corresponding hex codes to the left, you'll find they are 0x93 and 0x94.  If you get rid of those it should work for all.
```
00000000: 20 20 20 20 09 09 09 09 09 09 27 3c 62 3e 3c 73      ......'<b><s
00000010: 70 61 6e 20 73 74 79 6c 65 3d 22 66 6f 6e 74 2d  pan style="font-
00000020: 66 61 6d 69 6c 79 3a 20 73 65 72 69 66 3b 22 3e  family: serif;">
00000030: 27 2b 63 68 28 27 3c 27 29 2b 27 43 68 61 6f 73  '+ch('<')+'Chaos
00000040: 20 46 61 63 74 6f 72 27 2b 63 68 28 27 3e 27 29   Factor'+ch('>')
00000050: 2b 27 3c 2f 73 70 61 6e 3e 3c 2f 62 3e 20 27 2b  +'</span></b> '+
00000060: 63 68 28 27 2d 27 29 2b 27 20 41 20 63 68 61 6f  ch('-')+' A chao
00000070: 73 20 66 61 63 74 6f 72 20 72 61 6e 67 69 6e 67  s factor ranging
00000080: 20 66 72 6f 6d 20 31 20 74 6f 20 39 2e 20 54 68   from 1 to 9. Th
00000090: 65 20 68 69 67 68 65 72 20 74 68 65 20 6e 75 6d  e higher the num
000000a0: 62 65 72 2c 20 74 68 65 20 6d 6f 72 65 20 6c 69  ber, the more li
000000b0: 6b 65 6c 79 20 61 20 93 79 65 73 94 20 61 6e 73  kely a .yes. ans
000000c0: 77 65 72 20 69 73 20 61 6e 64 20 6d 6f 72 65 20  wer is and more 
000000d0: 75 6e 65 78 70 65 63 74 65 64 20 65 76 65 6e 74  unexpected event
000000e0: 73 20 6f 63 63 75 72 2e 27 2b 0a                 s occur.'+.
```

**Comment by shdwjk** [comment]
I went ahead and pushed that change in my current Pull Request: https://github.com/Roll20/roll20-api-scripts/pull/411

Hopefully that should sort it out very soon.

**Comment by pyromanci** [comment]
Sadly this did not fix it. 

I even re ran a check against the file looking for any other UTF characters. There were not any.

**Comment by shdwjk** [comment]
If you're still in contact with them and they are still having the issue, maybe have them PM me a join link and GM me on Roll20 and I can try and track down what's happening?

Are you getting the issue when you install from the 1-click?

**Comment by pyromanci** [comment]
I had just created a new game my self to test. 

I will send you a PM with the game link. 

The issue does only happen with the 1-Click install. If you paste in the script manually it works just fine. Though right now going to the API Scripts page gives you the UTF-8 error.

**Comment by shdwjk** [comment]
I'm relatively certain this is an issue of the Unicode Characters in the `description` property of the `script.json`.  I've made the correction in the above commit, which will hopefully fix it.

**Comment by aquaalex** [comment]
@pyromanci @shdwjk 
Hi has this been fixed now? If so please close the issue :)
(hello Aaron)
