### ISSUE TITLE
Genesys Dice Roller

### ISSUE THREAD

**Issue by Vyzzini** [Roll20/roll20-api-scripts#580]
The Success & advantage image for the ability dice (green D8) is incorrect.
It's set up on line 1265 of the script with the _https://i.imgur.com/v4cUwLN.png_ url, which is the success & advantage side of the proficiency dice (yellow D12).

**Comment by apathy-dude** [comment]
If this is not fixed already it will be fixed with 751

**Comment by apathy-dude** [comment]
I ran a quick test and this seems to be fixed on the website now.  Is the issue good to close?

**Comment by clevett** [comment]
I think so. I'll go ahead and close it just in case the poster doesn't come back to Github. Thanks again for fixing this.
