### ISSUE TITLE
How  do I install this in Roll20?

### ISSUE THREAD

**Issue by geoidesic** [Roll20/roll20-api-scripts#733]
The readme doesn't actually have an install section. It just says "this will be installed when you run this script" but it doesn't say _how_ to run the script.

**Comment by MadCoder253** [comment]
Hi geoidesic there are two ways to install a script, both require having a pro account. 

Go to your campaign page, it has "launch game", "Content", "Looking for Players", and "Settings"

Click on "Settings" and then click "Api Scripts"

On the tab "Script Library" there is a drop-down. Click the script you want to install. 
Or you can click "New Script" and copy/paste script to a new file.
