### ISSUE TITLE
Turnmarker script triggers blood status FX when it's token's turn.

### ISSUE THREAD

**Issue by redhenmedia** [Roll20/roll20-api-scripts#754]
Hi, 

I love using Status FX while gaming! During my last session when the Turnmarker script highlights the token, it triggers the blood status FX. I've been using the two scripts in conjunction for about a year with no issues up until this point. Please let me know if you need more information or would like to see for yourself on the roll20 server. Willing to help in any way I can in order to figure out/resolve the issue. Thanks!

UPDATE: RESOLVED. No errors from Status FX. the Turnmarker token on the map layer had the red icon on so Status FX was just doing its job. I just disabled it no blood effect. Thanks again for the great script!

**Comment by Cazra** [comment]
Glad to hear the problem was resolved! Would you mind closing the issue?

**Comment by clevett** [comment]
I'll go ahead and close the issue since its noted as resolved. :)
