### ISSUE TITLE
DupCharToken issue

### ISSUE THREAD

**Issue by G-G-G** [Roll20/roll20-api-scripts#814]
When trying to install this script from the One-Click Library, no error is reported, but it does not install.

As reported in the thread here: https://app.roll20.net/forum/post/7520756/chris-dickeys-duplicate-and-add-identifying-number-to-character-and-token-api-not-installing/

**Comment by ChrisDDickey** [comment]
I have been trying to figure this out, but with no luck. In the thread referenced above it was pointed out that the dependencies and conflicts entries of the json had a problem, but I fixed those, but the problem persists. 
Once again, the script works if you just press the "new script" button and paste the .js text in. It is that the one-click library is failing to install the script with ether the "add script" or "import" options. It just quietly fails. No error message or anything, it just fails to add the script. 
Can anybody tell WHY the script is failing to be added from the One-Click libary?

**Comment by ChrisDDickey** [comment]
How does one close an issue?
Issues #814 and #868 ought to be closed now, but I don't see any way to do so.

**Comment by G-G-G** [comment]
Looks like the original creator of the thread can close the issue. Just closed this one.
