### ISSUE TITLE
Door Knocker for One-click

### ISSUE THREAD

**Issue by Kurohyou** [Roll20/roll20-api-scripts#859]
@clevett, just wondering if we can get Door Knocker added to the approved.yaml for one-click inclusion.

**Comment by clevett** [comment]
It was not. My sincerest apologies. I need to add a pull request template for APIs. I frequently have difficulty distinguishing between new APIs and updates.

**Comment by Anduh** [comment]
It's in the 1-click now, so this issue have been solved.
