### ISSUE TITLE
Remove ItsATrap_theme_5E_OGL and Shaped.

### ISSUE THREAD

**Issue by Cazra** [Roll20/roll20-api-scripts#950]
Can we remove the 5E OGL and 5E Shaped It's A Trap theme scripts from the source tree, please? I've deprecated them long ago in favor of the 5E Generic It's a Trap theme, but I still get bothered from time to time by users who install and try to use them (even though they explicitly tell the user that they should use 5E Generic instead).

**Comment by Anduh** [comment]
@wing-it can these two APIs be removed from the One-Click install?

@Cazra I think you could make a PR and remove the two APIs from the https://github.com/Roll20/roll20-api-scripts/blob/master/approved.yaml file, they would then be removed from the Roll20 in-game API install menu.
