### ISSUE TITLE
Fumbler - Custom table - Unexpected token l in JSON

### ISSUE THREAD

**Issue by kiloforce** [Roll20/roll20-api-scripts#993]
When I create a custom sheet with custom Fumbler table, the parser fails with the following:

`The fumble chart handout has errors: Unexpected token l in JSON at position 2`

Sample custom sheet:
`[{low: 1, high: 50, result: "sad", effect: "I fall down"},{low: 51, high: 99, result: "verysad", effect: "something bad"}]`

**Comment by geoidesic** [comment]
Mine has a similar error:
```
The fumble chart handout has errors: Unexpected token l in JSON at position 7
```
